name: Build and Deploy

on:
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./shell
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: SHELL - Install dependencies
        working-directory: ./shell
        run: npm i

      - name: SHELL - Build
        working-directory: ./shell
        run: npm run build
      
      - name: MFE1 - Install dependencies
        working-directory: ./mfe1
        run: npm i

      - name: MFE1 - Build
        working-directory: ./mfe1
        run: npm run build:copy

      - name: HEADER - Install dependencies
        working-directory: ./header
        run: npm i

      - name: HEADER - Build
        working-directory: ./header
        run: npm run build:copy

      - name: FOOTER - Install dependencies
        working-directory: ./footer
        run: npm i

      - name: FOOTER - Build
        working-directory: ./footer
        run: npm run build
      
      - name: Copy compiled to deploy directory
        shell: bash
        run: |
          ls ~/work/mfe/mfe
          rm -r ~/work/mfe/mfe/compiled/
          mv ~/work/mfe/mfe/shell/dist/* ~/work/mfe/mfe/compiled/
          mv ~/work/mfe/mfe/mfe1/dist/* ~/work/mfe/mfe/compiled/
          mv ~/work/mfe/mfe/header/dist/* ~/work/mfe/mfe/compiled/
          mv ~/work/mfe/mfe/footer/dist/* ~/work/mfe/mfe/compiled/

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          name: github-pages
          path: ./compiled
          retention-days: 0

  deploy:
    needs: build

    permissions:
      contents: read
      pages: write
      id-token: write

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    runs-on: ubuntu-latest

    steps:
      - name: Deploy to Github pages
        id: deployment
        uses: actions/deploy-pages@v4.0.5


